### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by syjzwjj** [montyly/gueb#1]
when I compile on my ubuntu . It shows :

ocamlfind ocamlc -package piqirun.ext,piqilib,unix -c graph.ml
File "graph.ml", line 418, characters 30-44:
Error: Unbound value List.sort_uniq
OCamlMakefile:1076: recipe for target 'graph.cmo' failed
make[1]: **\* [graph.cmo] Error 2
make[1]: Leaving directory '/home/zwjj/gueb/src'
OCamlMakefile:761: recipe for target 'byte-code' failed
make: **\* [byte-code] Error 2

How to solve this problem ?

**Comment by montyly** [comment]
Hi,

Which is your Ocaml version ?
List.sort_uniq comes with Ocaml 4.02 or later.

I think that Ubuntu came with Ocaml 4.01 by default. You can upgrade Ocaml on Ubuntu by adding this repo : 

add-apt-repository ppa:avsm/ppa
apt-get install ocaml

Regards

**Comment by syjzwjj** [comment]
truly it's version problem and your command is work ! thanks !

**Comment by montyly** [comment]
perfect !
